development:
  gcm_url: https://android.googleapis.com/gcm/send
  gcm_sender_id: 343180867553
  gcm_api_key: IzaSyCKuLZhhi_EBbXsUX8na9BC3GHSz9gzYN8

test:
  gcm_url: https://android.googleapis.com/gcm/send
  gcm_sender_id: 343180867553
  gcm_api_key: IzaSyCKuLZhhi_EBbXsUX8na9BC3GHSz9gzYN8

production:
  gcm_url: https://android.googleapis.com/gcm/send
  gcm_sender_id: <%= ENV["GCM_SENDER_ID"] %>
  gcm_api_key: <%= ENV["GCM_API_KEY"] %>
