development:
  host: localhost
  port: 6379
  db: 0
  driver: :hiredis

test:
  host: localhost
  port: 6379
  db: 1
  driver: :hiredis

production:
  host: <%= ENV["REDIS_HOST"] %>
  port: 6379
  db: 0
  driver: :hiredis
