development:
  host: localhost
  port: 6379
  db: 2

test:
  host: localhost
  port: 6379
  db: 3

staging:
  host: localhost
  port: 6379
  db: 2

production:
  host: <%= ENV["REDIS_HOST"] %>
  port: 6379
  db: 2
